// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProbaMala.Data;

#nullable disable

namespace ProbaMala.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503135327_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProbaMala.Models.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FoundedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FoundedDate = new DateTime(1878, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Name = "Manchester United"
                        },
                        new
                        {
                            Id = 2,
                            FoundedDate = new DateTime(1892, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Name = "Liverpool FC"
                        },
                        new
                        {
                            Id = 3,
                            FoundedDate = new DateTime(1880, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 4,
                            FoundedDate = new DateTime(1902, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 2,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 5,
                            FoundedDate = new DateTime(1899, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 2,
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = 6,
                            FoundedDate = new DateTime(1899, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 3,
                            Name = "AC Milan"
                        },
                        new
                        {
                            Id = 7,
                            FoundedDate = new DateTime(1897, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 3,
                            Name = "Juventus"
                        },
                        new
                        {
                            Id = 8,
                            FoundedDate = new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 4,
                            Name = "Bayern Munich"
                        },
                        new
                        {
                            Id = 9,
                            FoundedDate = new DateTime(1909, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 4,
                            Name = "Borussia Dortmund"
                        },
                        new
                        {
                            Id = 10,
                            FoundedDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 5,
                            Name = "Paris Saint-Germain"
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = 2,
                            Name = "La Liga"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Serie A"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bundesliga"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ligue 1"
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayGoals = 1,
                            AwayTeamId = 2,
                            Date = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 2,
                            HomeTeamId = 1,
                            LeagueId = 1
                        },
                        new
                        {
                            Id = 2,
                            AwayGoals = 1,
                            AwayTeamId = 1,
                            Date = new DateTime(2024, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 1,
                            HomeTeamId = 3,
                            LeagueId = 1
                        },
                        new
                        {
                            Id = 3,
                            AwayGoals = 2,
                            AwayTeamId = 3,
                            Date = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 3,
                            HomeTeamId = 2,
                            LeagueId = 1
                        },
                        new
                        {
                            Id = 4,
                            AwayGoals = 2,
                            AwayTeamId = 5,
                            Date = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 2,
                            HomeTeamId = 4,
                            LeagueId = 2
                        },
                        new
                        {
                            Id = 5,
                            AwayGoals = 1,
                            AwayTeamId = 4,
                            Date = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 0,
                            HomeTeamId = 5,
                            LeagueId = 2
                        },
                        new
                        {
                            Id = 6,
                            AwayGoals = 0,
                            AwayTeamId = 7,
                            Date = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 1,
                            HomeTeamId = 6,
                            LeagueId = 3
                        },
                        new
                        {
                            Id = 7,
                            AwayGoals = 1,
                            AwayTeamId = 9,
                            Date = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 3,
                            HomeTeamId = 8,
                            LeagueId = 4
                        },
                        new
                        {
                            Id = 8,
                            AwayGoals = 3,
                            AwayTeamId = 1,
                            Date = new DateTime(2024, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeGoals = 2,
                            HomeTeamId = 10,
                            LeagueId = 5
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClubId = 1,
                            DateOfBirth = new DateTime(1985, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Cristiano",
                            LastName = "Ronaldo",
                            Nationality = "Portugal",
                            Position = 3
                        },
                        new
                        {
                            Id = 2,
                            ClubId = 1,
                            DateOfBirth = new DateTime(1993, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Harry",
                            LastName = "Maguire",
                            Nationality = "England",
                            Position = 1
                        },
                        new
                        {
                            Id = 3,
                            ClubId = 1,
                            DateOfBirth = new DateTime(1990, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            LastName = "De Gea",
                            Nationality = "Spain",
                            Position = 0
                        },
                        new
                        {
                            Id = 4,
                            ClubId = 2,
                            DateOfBirth = new DateTime(1992, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mohamed",
                            LastName = "Salah",
                            Nationality = "Egypt",
                            Position = 3
                        },
                        new
                        {
                            Id = 5,
                            ClubId = 2,
                            DateOfBirth = new DateTime(1991, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Virgil",
                            LastName = "van Dijk",
                            Nationality = "Netherlands",
                            Position = 1
                        },
                        new
                        {
                            Id = 6,
                            ClubId = 3,
                            DateOfBirth = new DateTime(2000, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Erling",
                            LastName = "Haaland",
                            Nationality = "Norway",
                            Position = 3
                        },
                        new
                        {
                            Id = 7,
                            ClubId = 3,
                            DateOfBirth = new DateTime(1991, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kevin",
                            LastName = "De Bruyne",
                            Nationality = "Belgium",
                            Position = 2
                        },
                        new
                        {
                            Id = 8,
                            ClubId = 4,
                            DateOfBirth = new DateTime(1987, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Karim",
                            LastName = "Benzema",
                            Nationality = "France",
                            Position = 3
                        },
                        new
                        {
                            Id = 9,
                            ClubId = 4,
                            DateOfBirth = new DateTime(1985, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Luka",
                            LastName = "Modric",
                            Nationality = "Croatia",
                            Position = 2
                        },
                        new
                        {
                            Id = 10,
                            ClubId = 5,
                            DateOfBirth = new DateTime(1988, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sergio",
                            LastName = "Busquets",
                            Nationality = "Spain",
                            Position = 2
                        },
                        new
                        {
                            Id = 11,
                            ClubId = 8,
                            DateOfBirth = new DateTime(1988, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            LastName = "Lewandowski",
                            Nationality = "Poland",
                            Position = 3
                        },
                        new
                        {
                            Id = 12,
                            ClubId = 8,
                            DateOfBirth = new DateTime(2003, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jamal",
                            LastName = "Musiala",
                            Nationality = "Germany",
                            Position = 2
                        },
                        new
                        {
                            Id = 13,
                            ClubId = 9,
                            DateOfBirth = new DateTime(1990, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Marco",
                            LastName = "Reus",
                            Nationality = "Germany",
                            Position = 3
                        },
                        new
                        {
                            Id = 14,
                            ClubId = 10,
                            DateOfBirth = new DateTime(1989, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Thomas",
                            LastName = "Tuchel",
                            Nationality = "France",
                            Position = 2
                        },
                        new
                        {
                            Id = 15,
                            ClubId = 10,
                            DateOfBirth = new DateTime(1998, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kylian",
                            LastName = "Mbappe",
                            Nationality = "France",
                            Position = 3
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent performance!",
                            MatchId = 1,
                            PlayerId = 1,
                            Score = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Solid defense",
                            MatchId = 1,
                            PlayerId = 2,
                            Score = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Great goal!",
                            MatchId = 3,
                            PlayerId = 4,
                            Score = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Defensive masterclass",
                            MatchId = 3,
                            PlayerId = 5,
                            Score = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Best striker in the league",
                            MatchId = 2,
                            PlayerId = 6,
                            Score = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Great midfield control",
                            MatchId = 2,
                            PlayerId = 7,
                            Score = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Clinical finishing",
                            MatchId = 7,
                            PlayerId = 11,
                            Score = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Impressive technical skills",
                            MatchId = 7,
                            PlayerId = 12,
                            Score = 8,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.smith@email.com",
                            FirstName = "John",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            Email = "maria.garcia@email.com",
                            FirstName = "Maria",
                            LastName = "Garcia"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alex.johnson@email.com",
                            FirstName = "Alex",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sofia.rossi@email.com",
                            FirstName = "Sofia",
                            LastName = "Rossi"
                        },
                        new
                        {
                            Id = 5,
                            Email = "lucas.silva@email.com",
                            FirstName = "Lucas",
                            LastName = "Silva"
                        });
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Club", b =>
                {
                    b.HasOne("ProbaMala.Models.Entities.League", "League")
                        .WithMany("Clubs")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Match", b =>
                {
                    b.HasOne("ProbaMala.Models.Entities.Club", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProbaMala.Models.Entities.Club", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProbaMala.Models.Entities.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Player", b =>
                {
                    b.HasOne("ProbaMala.Models.Entities.Club", "Club")
                        .WithMany("Players")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Rating", b =>
                {
                    b.HasOne("ProbaMala.Models.Entities.Match", "Match")
                        .WithMany("Ratings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProbaMala.Models.Entities.Player", "Player")
                        .WithMany("Ratings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProbaMala.Models.Entities.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Club", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.League", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Matches");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Match", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.Player", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("ProbaMala.Models.Entities.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
